import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/layouts/Navbar";

const exo2 = Exo_2({
  subsets: ["latin"], // specify the subsets (optional)
  weight: ["400", "700", "900"], // optional: choose the font weights you want to include
  style: ["normal", "italic"], // optional: define styles
  display: "swap", // specify the weights (optional)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo2.className} antialiased relative z-0 bg-primary`}>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <footer>
          <h2>This is Footer</h2>
        </footer>
      </body>
    </html>
  );
}
